# Generated by Django 3.0.6 on 2020-06-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SystemSecurityPlans', '0007_link_requires_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_characteristic',
            name='system_status',
        ),
        migrations.AddField(
            model_name='system_characteristic',
            name='system_status',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.PROTECT, to='SystemSecurityPlans.status'),
            preserve_default=False,
        ),
    ]
